#Welcome to the configuration of Chat+, this is the work in progress version, so it can be with some bugs.

#This is the format that the plugin uses to set the chat, right now it just admits '%DISPLAYNAME', but you can change the others things like the '<>'

format: <%DISPLAYNAME%>

#The motd is the message that the players see when they enter to the server, you can change it as you wish. Right now, it supports the '&' color code, and %PLAYER%.

motd:
 message: "Welcome to the server, %PLAYER%"
 activated: true