main: es.wiky.chat.Main
author: Wikijito7
name: ChatPlus
version: 0.2


commands:
  cnick:
   description: It is one of the main commands in the plugin, it let u do a lot of things.
  motd:
   description: It just change the motd
  chatplus:
   description: The main command of the plugin. 
   aliases: cp
